stages:
  - build
  - test
  - deploy

default:
  interruptible: true

windows-build-job:
  stage: build
  tags:
    - net::outside
    - user::xl_ci
    - os::win10
    - env::cmd
  script:
    - echo "Compiling the code..."
    - set PATH=D:\Qt\6.6.2\mingw_64\bin;D:\Qt\Tools\mingw1120_64\bin;C:\Program Files (x86)\Inno Setup 6;%PATH%
    - call .\build_setup.bat
    - .\InnoSetup\build\dlink_gdbserver_console.exe -v
    - echo "Compile complete."
  artifacts:
    when: always
    name: "nuclei-dlink_gdbserver-win32-${CI_COMMIT_SHA::8}"
    paths:
      - InnoSetup/*.exe
      - InnoSetup/*.zip
    expire_in: 15 day

      #windows-test-job:
      #  stage: test
      #  tags: windows-2022
      #  script:
      #    - echo "Running unit tests... This will take about 60 seconds."
      #    - sleep 60
      #    - echo "Code coverage is 90%"

      #windows-deploy-job:
      #  stage: deploy
      #  tags: windows-2022
      #  script:
      #    - echo "Deploying application..."
      #    - echo "Application successfully deployed."

linux-build-job:
  stage: build
  tags:
    - net::outside
    - env::shell
    - user::xl_ci
    - sw::qt
  script:
    - echo "Compiling the code..."
    - source ~/shareenv.sh
    - bash -x ./build_deb.sh
    - cd dpkg/Linux_v*
    - pwd
    - ldd ./opt/dlink_gdbserver/dlink_gdbserver_console
    - ./opt/dlink_gdbserver/dlink_gdbserver_console -v
    - echo "Compile complete."
  artifacts:
    when: always
    name: "nuclei-dlink_gdbserver-linux64-${CI_COMMIT_SHA::8}"
    paths:
      - dpkg/*.tar.gz
      - dpkg/*.deb
    expire_in: 15 day

linux-test-job:
  stage: test
  tags:
    - env::docker
    - net::outside
  image: ubuntu:20.04
  dependencies:
    - linux-build-job
  script:
    - tar -xzf dpkg/*.tar.gz
    - echo "Check dlink_gdbserver version"
    - ldd ./dlink_gdbserver/dlink_gdbserver_console
    - ./dlink_gdbserver/dlink_gdbserver_console -v


#linux-deploy-job:
#  stage: deploy
#  tags: ubuntu-20.04
#  script:
#    - echo "Deploying application..."
#    - echo "Application successfully deployed."
